### ISSUE TITLE
Site ile ilgili soru #3

### ISSUE THREAD

**Issue by alisher-kadraliev** [alisher-kadraliev/Akademi-Dunyasi#10]
ben siteye cookie ekledim ve ordan sormak lazım. Benim tarafından js ile yaptığım bu kabul ettikten sonra süresi dolduktan sonra daha bir defa sorması ve veri olarak isim saklama, bu konuda siznle konuşmak isterim yada nerden bakabilirim tam olarak eklediğimiz cookie çalışması.
ben düşündüğüm gibi 
Kullanıcı Tercihlerinin Saklanması: Cihazlar arasında daha kalıcı izleme için kullanıcının çerez tercihlerini bir veritabanında depolamak istiyorsanız, arka uç geliştiricinizin bunu gerçekleştirmek için bir API uç noktası oluşturması gerekecektir.

Sunucu Tarafı Mantığı: Kullanıcının onayına bağlı olarak sunucu tarafında ayarlanan çerezler varsa, arka ucun bu çerezi okuması ve buna göre hareket etmesi gerekecektir. .NET'te HttpContext.Current.Request.Cookies kullanarak çerezleri okuyabilirler.

Yasal Uyumluluk: Web sitenizin farklı yargı bölgelerinden (AB ve AB dışı gibi) kullanıcılar için farklı içeriği, özellikleri veya izlemesi varsa, arka ucun bu mantığı ele alması gerekebilir.

HttpOnly Çerezlerini Ayarlama: Bazı çerezler güvenlik nedeniyle yalnızca sunucu tarafında ayarlanabilir. Bu durumda arka ucun, kullanıcının izin verip vermemesine bağlı olarak bu çerezlerin ayarlanmasını yapması gerekecektir.

`HttpCookie userCookie = HttpContext.Current.Request.Cookies["cookieConsent"];
if (userCookie != null)
{
    // User has accepted cookies. Do something.
}
`
`HttpCookie userCookie = new HttpCookie("cookieName", "cookieValue");
userCookie.HttpOnly = true;
HttpContext.Current.Response.Cookies.Add(userCookie);
`

**Comment by malibuduck** [comment]
Ben seninle konuşmak isterim. ChatGPT ile değil :)
