### ISSUE TITLE
Sitenin Dikkat çeken pop up overlay content

### ISSUE THREAD

**Issue by alisher-kadraliev** [alisher-kadraliev/Akademi-Dunyasi#2]
@malibuduck Sitenin ana sayfada alta inince modal gibi soru çıkıcaktı ve sizden sormalıyım onun içeriğinde ne yazılır diye mesela "meraba bize başvur ``Başvur` buttonu" 
![image](https://github.com/alisher-kadraliev/Akademi-Dunyasi/assets/98706585/ba856246-1d08-492f-9eb2-3d281f7bba83)

**Comment by malibuduck** [comment]
Sitenin altına indiğinde. Hala daha merak ettikleriniz mi var? Bize başvurun sorularınızı yanıtlayalım. Adı Soyadı, telefon numarası  formu olmalı.
