### ISSUE TITLE
Anasite ile soru #2

### ISSUE THREAD

**Issue by alisher-kadraliev** [alisher-kadraliev/Akademi-Dunyasi#8]
![image](https://github.com/alisher-kadraliev/Akademi-Dunyasi/assets/98706585/7a1df97e-147e-4cf4-9360-5f7696693a3e)
fikir olarak oraya doldurabilecek content 
Tanıtım Mesajı: "Yeni ürünlerimizi görmek için burayı tıklayın!"
İndirim ve Promosyonlar: "Sadece bugüne özel %20 indirim! Kaçırmayın."
Önemli Bilgilendirme: "Web sitemiz bakım modundadır. En kısa sürede geri döneceğiz."
Müşteri Yorumları: "Bu ürünü çok sevdim, kesinlikle tavsiye ederim!" - Ahmet
Etkinlik Duyurusu: "20 Eylül'de gerçekleşecek webinarımıza kaydınızı yaptınız mı?"
Yeni Özellikler: "Artık mobil uygulamamızı da indirebilirsiniz!"
Genel Bilgilendirme: "COVID-19 sebebiyle teslimat sürelerimiz uzamıştır."

**Comment by malibuduck** [comment]
Güzelmiş kullanalım.
