### ISSUE TITLE
Anasite ile ilgili soru #3

### ISSUE THREAD

**Issue by alisher-kadraliev** [alisher-kadraliev/Akademi-Dunyasi#9]
![image](https://github.com/alisher-kadraliev/Akademi-Dunyasi/assets/98706585/a4855c87-c1ae-4b42-9f6a-66af06dbe898)
sitenizde zendesk kullanmıştınız ben onun aynısın mı?  ya da kendim mi yapıyım(zendeske benzeyen)?

**Comment by malibuduck** [comment]
Zendesk kullanmaya devam edeceğiz.  Şifresini veririm gerekirse renkleri ile oynarsın.
